import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

import { Providers } from '@/app/redux/providers'
import LogOut from "@/components/log-out";
import { ThemeProvider } from "@/provider/theme-provider";
import { ThemeToggle } from "@/components/ui/theme-toggle";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Providers>
              <div className="flex justify-end items-center mt-4 mr-8">
                <LogOut />
                <ThemeToggle />
              </div>
              {children}
              <Toaster />
            </Providers>
      </ThemeProvider>
        
        </body>
    </html>
  );
}
